### ISSUE TITLE
OSGI header Private-Package

### ISSUE THREAD

**Issue by kuseman** [mybatis/typehandlers-jsr310#18] opened 2016-10-14 09:02 UTC
I think there is something wrong in MANIFEST.MF generation.

In version 1.0.1 we have this:

**Private-Package: org.apache.ibatis.type**

Which makes all handlers invisble when running in for example Karaf.

When looking at the POM's (both this one and parent) it seems correct.
In parent we add Private-Package only if the property ${osgi.private} is set and it's not set in this projects pom from what I can see but still we get the header in MANIFEST.MF

**Comment by harawata** [comment] 2016-10-19 15:50
I am not familiar with OSGi, so I googled 'osgi private-package'.
These SO Q&As seem to suggest that the 'Private-Package' has no effect at runtime.

- http://stackoverflow.com/questions/13514123/what-does-the-private-package-manifest-header-do
- http://stackoverflow.com/questions/13878308/whats-the-deal-with-private-packages

How did you verify that the problem is caused by the MANIFEST.MF ?

**Comment by skapral** [comment] 2016-11-17 14:23
kuseman is right - without proper Export-Package declarations in MANIFEST.MF, this JAR is not usable in OSGi. Provided merge request with a fix.

**Comment by skapral** [comment] 2016-11-17 14:26
Probably it is worth also to put type handlers in some subpackage, like "org.apache.ibatis.type.jsr310", in order to avoid split-package issue with some other bundles providing type handlers. OSGi is very sensitive to split-package issue (https://nirmalsasidharan.wordpress.com/2010/09/02/split-packages-an-osgi-nightmare/).

**Comment by harawata** [comment] 2016-11-17 15:05
Fixed by #22 . Thanks for the help, @skapral !

And thank you for the info about the split-package issue, too.

Changing package is a little bit tricky, though.
Because [TypeHandlerRegistry](https://github.com/mybatis/mybatis-3/blob/3ad1988f4dbb59251c89ffc3bf2db40103c7bb7a/src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java#L131-L142) has references to the JSR-310 type handlers.

If it is actually causing troubles, we could move these type handlers to MyBatis core (it became possible just recently).
We haven't done it because it could be confusing and there was no good reason to justify it.

**Closed by harawata** 2016-11-17 15:05 UTC
